#! /usr/bin/env python3

import pathlib
import os
from pathlib import Path
import argparse
import xml.etree.ElementTree as ET
from common import *

parser = argparse.ArgumentParser(description="Argparse script.")
parser.add_argument(
    "--trg-lang", type=str, nargs="+", required=True, help="target language"
)
args = parser.parse_args()


def main():
    trg_lang = map(get_bcp47_locale, args.trg_lang)
    for l in trg_lang:
        print(f"Generating for language {l}")
        out_dir = PROJECT_ROOT / "xliff" / Path(l.replace("-", "/"))
        out_dir.mkdir(parents=True, exist_ok=True)
        for t in TEMPLATE_XLIFF_LIST:
            xlf = ET.parse(t)
            root = xlf.getroot()
            root.insert(
                0,
                ET.Comment(
                    "This file is automatically generated. Do not update this file directly by hand! Use `update-xliff.py`."
                ),
            )
            root.attrib["trgLang"] = l
            ET.indent(xlf)
            xlf.write(
                out_dir / t.name,
                encoding="UTF-8",
                xml_declaration=True,
                short_empty_elements=False,
            )


if __name__ == "__main__":
    main()
